function Banner_Card() {
    return (
        <>
        <div className="test">
            <p>
                Lorem ipsum dolor sit amet consectetur adipisicing elit. Similique odit provident facere neque harum cumque qui, voluptatum est praesentium consequatur debitis magni aliquid quo dignissimos amet minima nihil assumenda accusamus.
                Lorem ipsum dolor, sit amet consectetur adipisicing elit. Dicta perferendis vel rerum deleniti consectetur aliquid minus reprehenderit dolores neque distinctio praesentium debitis fugiat rem, repellendus eligendi modi inventore dolorem eos!
                Eligendi voluptas consequatur veniam, eius cumque nesciunt et fuga! Nesciunt iure est ipsum odit dolore. Eum cupiditate recusandae eos ipsum, cum delectus itaque consequuntur, nesciunt, accusamus voluptates ratione fuga porro!
                Atque porro explicabo autem unde cupiditate laudantium maxime eum labore nisi quisquam? Deleniti placeat perferendis delectus voluptatem! Incidunt vero praesentium repellendus omnis officiis odio laudantium voluptates, dolores assumenda asperiores earum!
                Provident aliquam rerum iure magni beatae, odit hic harum quidem necessitatibus quae dolores dicta excepturi eos ratione obcaecati ab omnis debitis voluptatem optio voluptas sapiente officia quas! Perferendis, eaque repellat!
                Cupiditate eligendi omnis impedit, architecto eaque accusamus mollitia velit necessitatibus maxime tenetur ab qui, vel beatae. Maxime saepe nobis aperiam quae cumque exercitationem quas consequuntur voluptatibus autem cupiditate, et nisi.
                Modi labore quaerat quo dolorum officia veritatis quidem natus sint, id sunt! Exercitationem voluptatum, ullam consectetur, est a velit vel esse, consequuntur tempore minima deleniti tempora doloremque dolor facilis nisi.
                Perspiciatis autem culpa eligendi! Voluptas recusandae velit, harum delectus atque fugiat earum quas voluptatem, dolore dignissimos sunt iusto, illum cum maxime eligendi. Facilis adipisci, at earum labore assumenda nisi voluptates!
                Molestiae quaerat amet dignissimos. Nostrum nulla doloribus ducimus facilis quo magnam eum tenetur provident. Inventore, velit modi. Vel eum error itaque officiis, voluptatem blanditiis praesentium ad omnis nisi. At, corporis!
                Debitis adipisci ipsa cupiditate deserunt cum, quasi consectetur doloremque beatae ut harum, eos ea accusantium enim velit? Optio alias esse ipsa at praesentium magni quaerat modi? Atque, vero quia! Dolorum.
                Asperiores, minus dignissimos? Reprehenderit hic autem eius alias illo minima, praesentium laborum blanditiis voluptates modi recusandae nulla illum libero veniam rem iure harum suscipit distinctio architecto! Voluptatem ratione nesciunt dolor!
                Tenetur repellendus aliquid, facilis corrupti eos ut adipisci officiis eaque quidem ipsam unde veritatis minus iusto dolore veniam natus voluptatem repudiandae quasi? Voluptate deserunt quidem iusto ad sint, laboriosam voluptatum.
                Praesentium reprehenderit autem quasi dolorem. Eaque sit accusantium magni fugiat labore enim nobis debitis. Tempore asperiores impedit, vero atque est, dolorem voluptate non dignissimos id dolore, totam exercitationem sunt fuga.
                Ab ad dignissimos earum voluptas, quam ipsam, accusamus et esse, iusto aspernatur voluptatum obcaecati repellat qui eligendi numquam! Tempora ducimus hic et placeat nobis? Quibusdam libero eius perferendis tempora maiores.
                Cum eos aliquam molestiae non natus nulla consequuntur quis magni rerum dolorum? Expedita maxime repellendus, possimus voluptas minima suscipit praesentium totam corporis saepe accusantium, deleniti dolore iusto incidunt fuga porro!
                Blanditiis adipisci illo magnam saepe libero omnis voluptatum excepturi ratione, a accusamus cumque laudantium deserunt labore rerum molestias dolor odit enim temporibus eius ea expedita deleniti laborum quia sit? Ullam.
                Ipsa nostrum beatae quos quidem quod asperiores praesentium quaerat minus similique hic eligendi dolorum iusto aspernatur aut necessitatibus, neque doloribus placeat accusantium omnis culpa. Quo doloribus modi obcaecati mollitia expedita?
                Veniam iste tempore ex, dicta aliquam incidunt fugiat expedita, hic provident harum fuga earum saepe similique, eum repellendus. Vitae magni distinctio maiores dolorem nisi facilis adipisci temporibus reiciendis voluptates. Numquam?
                Dolore quia quibusdam voluptas veniam blanditiis cupiditate ea non deserunt earum, dignissimos quod, adipisci obcaecati? Nulla ducimus eveniet eos sed fuga dolore fugiat, ipsum officiis. Tenetur dolore eveniet eaque consectetur.
                Optio labore nesciunt facilis qui! Quam, eos odit, quae recusandae, expedita enim similique illum soluta id dicta omnis provident. Blanditiis, illo numquam possimus consectetur nobis dicta nisi provident sequi explicabo.
                Quos nisi hic magnam, labore voluptate similique doloribus, nobis consequuntur temporibus quam doloremque. Illum ullam explicabo quas, aspernatur, rerum minima quisquam impedit voluptatem hic voluptas illo dolores alias. Officiis, doloremque?
                Dolorem distinctio consectetur alias sequi voluptate hic odit? Perspiciatis at nobis tenetur mollitia, incidunt ipsum, exercitationem soluta facere esse modi quam assumenda? Quidem, nobis obcaecati natus accusantium neque nostrum tempore.
                Nisi, non ad? Necessitatibus ex debitis iste expedita laborum similique dicta aliquid neque quas, ratione repellat illum amet veniam repellendus distinctio sequi, nulla culpa voluptate! Eaque expedita at recusandae corrupti!
                Rem debitis assumenda voluptas illo deleniti expedita velit doloribus, necessitatibus rerum exercitationem ipsa dolores voluptate sed eaque tenetur, reiciendis fugiat adipisci molestias facere est, quidem inventore! A consequatur delectus hic.
                Vitae pariatur quo sequi sed numquam quibusdam fugit porro culpa delectus libero reiciendis, iusto voluptate dolor deleniti dolores natus quas molestias maxime accusantium optio nihil illum enim, tempora excepturi. Quasi.
                Accusamus alias fuga corrupti voluptatem reiciendis quidem. Molestiae, quae! Suscipit officiis quam, excepturi libero porro eveniet voluptates labore perferendis atque dicta, consectetur dolor obcaecati repudiandae iste reprehenderit fugiat doloribus? Eaque.
                Voluptatum sunt eius praesentium aliquam unde exercitationem eligendi nisi est esse delectus fuga, quaerat quod nesciunt facilis assumenda nobis culpa aspernatur iste ipsam id. Ipsam cumque et laudantium accusamus blanditiis.
                Consectetur, pariatur consequatur eum perspiciatis cum optio dolorum provident quia corrupti culpa sit, sapiente deserunt, ab molestiae! Suscipit deleniti quae eos aut praesentium ullam assumenda dolorem pariatur? Dolore, possimus laudantium.
                Minima quia aliquid ipsam asperiores ab! Aliquid, accusantium, illo optio eveniet ut doloremque officiis ratione velit voluptates reprehenderit magnam provident a incidunt nesciunt error maxime fuga quis doloribus, exercitationem facilis.
                Unde obcaecati, dolor tempore ad id repudiandae, cupiditate nulla eaque blanditiis velit, assumenda quo quia eligendi! Ullam, aliquid asperiores optio eos deserunt, ipsum dolore voluptas doloribus quia, id quae nobis?
                Tenetur, alias similique delectus quasi cupiditate sed harum. Magnam inventore iusto perspiciatis facilis, nemo laboriosam similique accusamus dicta ut quidem itaque, necessitatibus corrupti reiciendis repellat, explicabo neque quis esse eius?
                Nesciunt maxime temporibus quo a laborum quidem architecto dignissimos vero vitae, consequatur nisi reiciendis itaque neque voluptate esse excepturi voluptates facilis et similique ratione cupiditate ad! Natus dolorem accusantium eaque!
                Earum et, assumenda neque, temporibus tempora iusto esse quis enim minus incidunt illo aliquid officia voluptates. Nemo harum doloribus quaerat delectus nulla, maxime accusamus iure ullam. Amet magnam quidem tempora.
                Amet blanditiis doloremque soluta officia repudiandae, facere labore cumque natus quidem a praesentium iste! Impedit illo, nisi illum quidem corporis asperiores ducimus quae nemo facilis soluta facere commodi totam quo!
                Suscipit optio provident, sunt saepe eius aliquid similique eum adipisci pariatur impedit nulla quas ratione commodi labore et nostrum, velit deserunt! Sint, repellat! Incidunt repellendus molestiae hic dignissimos sunt laudantium.
                Possimus vero totam laudantium. Corrupti sed, perspiciatis sapiente maiores molestias cumque repellendus facere quis, tempora nam laborum aliquid illo illum? Minus ipsum dignissimos molestiae explicabo doloribus sunt nisi officia sapiente?
                Id nostrum fuga totam temporibus expedita dicta aliquid, saepe mollitia sed suscipit, optio doloremque reprehenderit excepturi numquam enim obcaecati vitae maxime rem odit eum dolorem accusantium delectus doloribus! Voluptates, nam?
                Similique magnam ipsa iusto repellat ducimus? Explicabo eos officia ipsum sequi nisi sapiente nostrum voluptatibus architecto animi assumenda modi dignissimos possimus distinctio et, qui quibusdam dicta, quasi deleniti maiores. Magni?
                Sint necessitatibus blanditiis consequatur voluptatem! Quas esse, sint dolorem quisquam ea atque alias soluta accusamus consequuntur quia numquam natus distinctio saepe accusantium rerum ut dignissimos rem dolores laboriosam. Dolore, necessitatibus?
                Id tenetur exercitationem in ducimus illo hic? Velit ut id adipisci rerum. Et animi nisi nesciunt tenetur earum ratione iure officiis eum, alias repellat. Amet debitis maiores mollitia sequi non?
                Quos tempora eligendi aut error fugiat iste voluptates, facere iusto, debitis sunt tenetur in, sequi tempore nulla. Est laborum deleniti eveniet vero eligendi, doloribus, necessitatibus, repellendus minus in beatae voluptatibus!
                Fugit saepe quaerat sequi accusantium doloribus commodi similique quod iusto consequatur quisquam, molestias, totam enim ab dolore! Vitae numquam repellendus, dolorem officia, magni enim repellat eligendi deleniti et ut molestias!
                Porro eum nesciunt reiciendis. Eius dolor soluta cupiditate fugiat error reiciendis sed laboriosam distinctio, saepe possimus odio architecto aspernatur incidunt earum eos est perferendis consequuntur deserunt magnam reprehenderit. Vitae, hic.
                Praesentium, quo iste at, nulla ullam saepe quasi perferendis culpa beatae aliquam sequi doloribus dolore molestiae autem consequuntur! Natus quibusdam modi consequuntur distinctio esse delectus iure ad ipsum quo consequatur.
                Explicabo cum libero cupiditate, atque aspernatur nam excepturi necessitatibus quo sapiente amet officiis rem earum. Voluptate voluptatibus voluptatem voluptas explicabo, labore asperiores animi omnis, reiciendis minima alias, in vitae ea.
                Illum accusantium vel esse asperiores, expedita aut cumque impedit est, perferendis adipisci eius dolorem eligendi eos rem dolores aliquam. Assumenda obcaecati nisi atque iste minus vero ad harum doloribus nam.
                Maiores quo rerum odit, assumenda quibusdam voluptas? Aliquid atque est amet, ducimus totam quibusdam iure eum alias facere fugiat aut consectetur. Possimus saepe commodi cupiditate. Quos dolorum recusandae magni doloribus.
                Incidunt facilis accusantium iusto repudiandae sit numquam odit provident laborum tempore excepturi est delectus iure, qui saepe cumque dolorum. Amet explicabo minus dolores architecto unde quia omnis dolorem consequuntur laudantium!
                Voluptatibus necessitatibus minus nostrum odio possimus laborum quam commodi veniam molestias pariatur excepturi quos ipsa voluptatem facere, debitis inventore laboriosam velit corporis molestiae. In accusantium assumenda officiis aliquid nihil velit.
                Ab, laboriosam quisquam! Illum magnam cum commodi rem doloribus quae ullam eveniet excepturi dicta facere illo iste minima minus eum molestias nihil a dolores placeat pariatur, similique, tenetur cumque! Quisquam.
                Nihil numquam consectetur fuga accusantium voluptatem tenetur, iusto nobis autem obcaecati dolore quaerat! Inventore, magnam. Dolorem corporis eligendi necessitatibus minus esse odio unde vel ex libero, delectus eos asperiores aperiam!
                Voluptatem cum distinctio est enim. Est at doloremque assumenda, aut, id doloribus harum quaerat ratione cupiditate distinctio natus a architecto modi nostrum quas beatae ipsa rem libero minus voluptatibus! Neque?
                Natus molestiae perferendis expedita optio aspernatur explicabo quisquam, dolorum, odio quam dicta corporis eos soluta laborum blanditiis cupiditate eveniet libero sint laudantium asperiores aliquam sapiente rerum? Distinctio ipsum quod velit!
                Quaerat perspiciatis odio qui quo est. Libero magnam eum veniam, asperiores error dolore explicabo. Repudiandae delectus asperiores, corrupti quisquam laborum sapiente doloribus totam unde sint voluptas ab voluptatibus vero tempora!
                Dolore porro dolores eius quis fugiat aliquid sapiente, magni repudiandae labore vero perspiciatis nemo nulla eligendi, provident rem cumque nostrum natus? Dolor quo molestias mollitia magni dignissimos laboriosam, non deleniti.
                Quaerat facere deleniti, cumque similique fugit architecto saepe quos veritatis quidem adipisci quisquam cum vel consectetur provident illo perferendis eius ullam velit voluptatem nulla iste sint corporis ratione non. Consequuntur?
                Quas ea ratione nemo inventore? Recusandae odit rerum quod repellendus, tenetur sunt velit assumenda totam asperiores similique accusantium mollitia sed consequuntur provident dolor quaerat iste at ipsam, doloribus optio consectetur!
                Molestias minima repudiandae odio autem libero harum incidunt magnam doloremque at, quo nemo fugit molestiae totam? A odit labore porro eius cumque fugit saepe dolore repellat, ipsa cupiditate dolores corrupti.
                Nesciunt voluptates fuga hic atque! Laboriosam illo repudiandae deserunt perferendis reprehenderit cum nostrum dolor. Reiciendis culpa minima corporis ut iste architecto ullam optio, obcaecati eum, doloremque possimus aliquam dignissimos necessitatibus?
                Aut temporibus quasi fuga est. Itaque qui placeat quis tempora officia voluptas mollitia neque excepturi officiis perspiciatis! Magnam commodi voluptates cum eius labore. Architecto doloribus excepturi autem maiores voluptatem non!
                Minima voluptas culpa error sunt minus reprehenderit nostrum ipsa fugit ea officia dolores fuga magnam, libero laudantium, pariatur aspernatur excepturi eius. Rerum, repudiandae! Sequi temporibus odio eaque natus, distinctio earum!
                Laboriosam error labore incidunt quibusdam temporibus corrupti repellat deleniti eum tempora voluptatum ab nisi architecto laudantium, ex itaque, doloribus illum velit non ipsa! Fugiat reiciendis quis, placeat at eligendi corrupti.
                Labore, eos. Velit maiores, fugiat rem cumque ad saepe ut eligendi assumenda sequi quo expedita distinctio nobis sint sed exercitationem fugit, similique, nulla quisquam! Hic dignissimos optio tempore adipisci libero.
                Est blanditiis quas quidem ullam, debitis dicta minima voluptates voluptatum voluptate eum aspernatur expedita autem, odio similique cumque! Magnam, dolore distinctio deleniti nobis eos impedit vel iure in ducimus autem.
                Dolorem tempora provident soluta deleniti optio? Quae suscipit optio iusto doloremque est! Nisi harum eaque ipsum, expedita minima beatae. Nesciunt ducimus nihil dolorem, eos labore porro ipsam qui recusandae ipsa.
                Corporis, eaque eum fuga excepturi accusamus aliquid nulla error dolorem enim quisquam assumenda eligendi magnam cupiditate ullam, sit fugiat atque molestias quibusdam laboriosam aspernatur quo. Corporis nostrum ex unde illum.
                Sunt accusantium provident totam, dignissimos doloremque eveniet asperiores praesentium, ratione ea facere voluptates expedita dolor, inventore perferendis architecto aliquid accusamus. Odit omnis consectetur id recusandae unde facilis voluptate asperiores in.
                Officia illum inventore rerum ipsa facere laborum! Repellat voluptatum minima a eligendi ratione fuga illo distinctio vero quibusdam iusto, corrupti nulla aut repellendus animi. Dolores odio sapiente pariatur illum nesciunt!
                Quis alias laboriosam architecto aliquam exercitationem expedita enim distinctio nobis sunt, non cum nostrum culpa quibusdam placeat quasi quaerat eos cupiditate tempore error incidunt voluptatum. Voluptates vel dignissimos magnam dolorem.
                Eius quidem iste, fugiat dolor fugit dolorum dicta optio necessitatibus quibusdam sed iure eos accusamus excepturi impedit quo soluta vitae asperiores totam quia, ullam pariatur? Fugiat, molestiae totam? Similique, at?
                Nostrum quo corrupti ipsa, nobis atque nihil fuga repellat quaerat, deserunt, vel velit fugit! Repudiandae similique labore excepturi provident deleniti optio officia explicabo doloribus incidunt tempore. Voluptates laboriosam repudiandae debitis.
                Minima facere maxime nam quasi doloribus perferendis id rerum similique velit dolorum ab blanditiis incidunt delectus, esse praesentium repellendus. Aspernatur molestias debitis eveniet maxime incidunt sint officia facilis eaque laborum.
                Eaque delectus tempora quo voluptas quaerat ipsam libero, quibusdam maiores corrupti ut, officiis possimus minima quos quidem voluptatibus quasi ea, soluta dignissimos dolorem? Quasi suscipit necessitatibus, debitis voluptates animi eius!
                Blanditiis, recusandae? Cumque asperiores consequuntur ad a reiciendis recusandae minima perferendis, deleniti maxime, vero ab. Nihil, dolores sunt est, atque repellat, porro numquam aliquam aut ex neque error? Ducimus, doloremque?
                Modi esse vero quos amet molestias dicta deleniti porro debitis ab, adipisci, repellendus maiores consectetur nisi accusantium neque quidem optio eaque officiis cumque autem minus. Sed voluptatem iure dolorum tenetur.
                Officiis cupiditate molestiae id eaque. Quibusdam repudiandae consectetur eius quo aut, eveniet deleniti perspiciatis quis laboriosam, nemo dolorum vero adipisci possimus nostrum ex. Laboriosam beatae reprehenderit officiis vel fuga. Itaque.
                Nemo eos ea numquam. Nostrum eius culpa in inventore et mollitia, eligendi fugiat laboriosam aliquam consequatur? Corrupti similique mollitia labore veniam veritatis placeat, omnis rerum asperiores voluptates sed accusamus molestias!
                Repellat officia atque illo saepe aut quia ad facilis amet, voluptates, tempora ipsa sapiente quas aliquid sit unde tenetur ratione. Eaque quasi incidunt adipisci saepe aspernatur ipsum perferendis ullam cupiditate.
                Dicta cumque sapiente minima corporis voluptatibus quis quibusdam odio, nihil ad voluptatum. Maxime eos sint aperiam aliquid adipisci, fuga atque iure asperiores consequatur omnis excepturi quis numquam ut aut dignissimos!
                Ipsa rerum sed dolorum numquam fuga illo quibusdam consequuntur aperiam necessitatibus cupiditate, explicabo porro reiciendis? Est necessitatibus eum maiores quos accusantium sequi, enim veniam modi nobis dignissimos aliquam ipsam libero.
                Nemo officiis vel veniam omnis voluptate libero modi sint molestiae dicta vero? Illo dolores sit architecto, ducimus id itaque ratione. Officiis molestias delectus velit, culpa eveniet laborum vel repellendus hic?
                Eligendi facere quas molestiae debitis, nulla eum vero excepturi doloribus et voluptatum dolorum placeat aliquid temporibus ratione tenetur. Et provident, ad sint deserunt omnis quia aut corporis ex earum laboriosam.
                Earum unde consectetur libero odio omnis, possimus temporibus perspiciatis quia animi quae inventore consequuntur iusto molestiae soluta asperiores ducimus neque fugit harum adipisci aut sapiente sed dignissimos! Repellat, officia culpa.
                Sequi eaque repellendus porro cumque corporis! Nesciunt voluptatibus natus sequi cupiditate veniam odit, provident tenetur reprehenderit inventore assumenda! Impedit dolor dignissimos rerum nostrum perspiciatis vel delectus minus expedita soluta iure.
                Repudiandae eaque saepe impedit blanditiis officia quaerat molestiae delectus, vel optio necessitatibus consequuntur laborum? Error officiis ea iste, accusamus delectus corporis qui animi. Earum, similique perferendis? Fugiat laborum adipisci earum.
                Eaque, a perspiciatis placeat vitae blanditiis doloribus nesciunt, ea enim hic beatae soluta dicta. Quaerat aut nostrum perspiciatis quae quis quisquam cupiditate tempora et veritatis repellat itaque, quia doloribus sed.
                Dolore optio aperiam obcaecati alias delectus nesciunt totam odio quos! Labore consectetur eveniet earum minima unde hic nobis voluptas aliquam aut! Corrupti recusandae doloribus, praesentium voluptate perspiciatis commodi quam exercitationem?
                Vel quis aliquam tenetur voluptatem, deleniti consequatur ullam saepe recusandae velit, officiis error iste sit quia distinctio est dolores eligendi beatae doloribus! Inventore ea assumenda iusto architecto, molestias doloribus alias.
                Voluptates, ut nihil voluptatibus incidunt numquam consequatur perspiciatis dolor, error ratione sunt quae repudiandae harum nam, aliquam quis eaque laboriosam debitis quaerat quidem sed ex dicta sapiente recusandae. Officia, facere?
                Vero nesciunt, nulla rem at porro numquam, quos voluptate dolore, hic autem dignissimos quisquam ducimus culpa magnam natus! Nobis voluptatem exercitationem, in voluptatum culpa quibusdam quod iste consequatur impedit. Molestiae!
                Beatae illo ad id cum laudantium aliquid eum adipisci mollitia officiis inventore reprehenderit autem repellendus laborum omnis necessitatibus eaque quibusdam voluptate consectetur sunt modi illum, expedita provident quod porro. Porro!
                Asperiores necessitatibus esse quaerat sequi fuga aperiam quas doloremque quasi amet perspiciatis eum blanditiis minus quo sed nesciunt reprehenderit dolorem adipisci, officia autem? Facere unde soluta autem nihil dolorem architecto.
                Omnis, nisi fugit? Nisi commodi cupiditate blanditiis harum quis molestias similique est, dolores hic, maiores excepturi iusto, rem reiciendis repellendus. Sint voluptas odit sunt blanditiis at doloremque rem excepturi officia.
                Quae dicta fugit officiis odio nihil ipsa cumque nisi nulla deserunt sint, impedit, vitae voluptates adipisci pariatur? Aliquid dignissimos nulla reiciendis in natus, earum quaerat quam necessitatibus sunt quas expedita.
                Ab maiores quod sint itaque, nobis praesentium hic maxime obcaecati fuga fugit, dolorem repellendus totam ducimus molestias reiciendis veniam, doloribus rerum autem? Voluptatibus non magnam officiis rem commodi labore earum.
                Minus omnis commodi, ex saepe modi eius dolores quam nulla aliquam sit corrupti delectus officiis voluptate iste iure dolore ipsam ullam cum ut quia. Natus blanditiis modi ducimus sequi dicta.
                Voluptatum quidem dignissimos, in dolorum velit enim esse excepturi corporis, quod doloribus molestias rem itaque, culpa omnis deleniti corrupti nesciunt repudiandae quibusdam blanditiis modi nostrum dolor nulla! Architecto, dolores aperiam?
                Dolorum sed accusantium maxime incidunt, fugiat animi saepe esse quasi illum soluta nulla odio doloribus a? Alias est perferendis, accusamus, impedit, itaque quisquam magni enim reiciendis quo earum ullam. Asperiores!
                Quibusdam sunt fuga dolore, animi itaque explicabo molestiae dolores, commodi placeat eveniet minima doloribus quas maxime nemo blanditiis dolor vero ipsa magni provident cum error ipsum? Hic nemo ipsam suscipit.
                Cumque alias debitis similique dolores blanditiis natus magni, repellat a vitae ipsum beatae deleniti officiis magnam non? Architecto perferendis maiores ex hic quia possimus dolorum dolore, iure accusantium explicabo cumque.
                Impedit maiores repellat, voluptates accusantium vitae et expedita repellendus voluptatibus ea cupiditate nam animi. Facilis itaque, quod ea, non totam sit consectetur iste officia aliquid dignissimos, fugiat sed culpa quae!
            </p>
        </div>
        </>
    );
};

export default Banner_Card;